# Generated by Django 2.2.14 on 2021-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='autograph',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='性别'),
        ),
    ]
