# Generated by Django 2.2.14 on 2021-06-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '专题课程', 'verbose_name_plural': '专题课程'},
        ),
    ]
