# Generated by Django 2.2.14 on 2021-06-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210615_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscount',
            name='sale',
            field=models.TextField(blank=True, help_text='\n    不填表示免费；<br>\n    *号开头表示折扣价，例如*0.82表示八二折；<br>\n    -号开头则表示减免，例如-20表示原价-20；<br>\n    如果需要表示满减,则需要使用 原价-优惠价格,例如表示课程价格大于100,优惠10;大于200,优惠25,格式如下:<br>\n    满100-10<br>\n    满200-25<br>\n    ', null=True, verbose_name='优惠公式'),
        ),
        migrations.CreateModel(
            name='CourseExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加数据的时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改数据的时间')),
                ('expire_time', models.IntegerField(blank=True, help_text='有效期按天数计算', null=True, verbose_name='有效期')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程价格')),
                ('expire_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='提示文本')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_expire', to='course.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程有效期',
                'verbose_name_plural': '课程有效期',
                'db_table': 'ly_course_expire',
            },
        ),
    ]
