# Generated by Django 2.2.14 on 2021-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210616_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果价格为0，那么该课程没有永久有效选项', max_digits=6, verbose_name='课程原价'),
        ),
    ]
