# Generated by Django 2.2.14 on 2021-05-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210525_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='updated_time',
        ),
    ]
